#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/simulacion
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: mysql
#    show-sql: true
#spring:
#  datasource:
#    url: jdbc:sqlserver://localhost
#    username: sa
#    password: P@55w0rd
#    platform: mssql
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database: SQL_SERVER
#    show-sql: true
spring:
    datasource:
            username: postgres
            password: 123456
            url: jdbc:postgresql://localhost:5432/simulacion
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate.ddl-auto: create-drop
        show-sql: true
